/* Palette generated by Material Palette - materialpalette.com/amber/blue-grey */
const theme = {
  palette: {
    darkPrimary: "#FFA000",
    default: "#ffc107",
    lightPrimary: "#ffecb3",
    accent: "#607d8b",
    text: "#212121",
    textAlternative: "#ffffff",
    secondaryText: "#757575",
    divider: "#bdbdbd",
    background: "#ffffff",
    black: "#000000",
    softText: "#777777",
  },

  fonts: {
    title: "Dancing Script",
    text: "Oxygen",
  },
};

export default theme;
