/* Palette generated by Material Palette - materialpalette.com/amber/blue-grey */
const theme = {
  palette: {
    // darkPrimary: "#ffa000",
    darkPrimary: "#ffeb3b",
    default: "#ffc107",
    lightPrimary: "#ffecb3",
    accent: "#607d8b",
    text: "#212121",
    textAlternative: "#ffffff",
    secondaryText: "#757575",
    divider: "#bdbdbd",
    background: "#ffffff",
  },
};

export default theme;
